#!/bin/bash

class=$1
# class="FragTrap"

hdr="$class.hpp"
src="$class.cpp"
tmp_src="$hdr                                                      "
comment_source_name=${tmp_src:0:20}
dateandtimeandstuffofthings=$(date)

cat > $hdr << EOF
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * **
**                                                                                             **
**          oliver belanger - obelange                                                         **
**          $comment_source_name                                                               **
**                                                                                             **
**                                                                                             **
**          $dateandtimeandstuffofthings                                                       **
**                                                                                             **
**                                                                                             **
** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

EOF

echo "#include <iostream>" >> $hdr
echo "" >> $hdr
hh="_H"
printf "#ifndef " >> $hdr
echo "$class$hh" | awk '{print toupper($0)}' >> $hdr
printf "# define " >> $hdr
echo "$class$hh" | awk '{print toupper($0)}' >> $hdr
echo "" >> $hdr
echo "class $class" >> $hdr
echo "{" >> $hdr
echo "" >> $hdr
echo "public:" >> $hdr
echo "    $class(void);" >> $hdr
echo "    $class(void);" >> $hdr
echo "    $class(const $class& cp);" >> $hdr
echo "    ~$class(void);" >> $hdr
echo "" >> $hdr
echo "    $class&   operator=(const $class& rhs);" >> $hdr
echo "" >> $hdr
echo "private:" >> $hdr
echo "" >> $hdr
echo "};" >> $hdr
echo "" >> $hdr
echo "#endif" >> $hdr
















