#!/usr/bin/env python
import sys
import datetime
import glob



mm="main.cpp"
tmp_src = mm+"                                                      "
comment_source_nam = tmp_src[:20]
dateandtimeandstuffofthing=str(datetime.datetime.now())

header = """\
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * **
**                                                                                             **
**          oliver belanger - obelange                                                         **
**          {000000000000000000}                                                               **
**                                                                                             **
**                                                                                             **
**          {000000000000000000000001}                                                         **
**                                                                                             **
**                                                                                             **
** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

""".format(comment_source_nam, dateandtimeandstuffofthing)

wr = []
wr.append(header)
wr.append("#include <iostream>\n\n")

hdrs = glob.glob("*.hpp")

for x in hdrs:
	wr.append("#include \"{0}\"\n".format(x))

wr.append("""
int		main(void)
{
	return 0;
}
""");


# echo "" >> $mm
# echo "int       main(void)" >> $mm
# echo "{" >> $mm
# echo "    return 0;" >> $mm
# echo "}" >> $mm

f = open(mm, "w")

for x in wr:
	f.write(x)

f.close()