#!/bin/bash

mm="main.cpp"
tmp_src="$mm                                                      "
comment_source_name=${tmp_src:0:20}
dateandtimeandstuffofthings=$(date)

cat > $mm << EOF
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * **
**                                                                                             **
**          oliver belanger - obelange                                                         **
**          $comment_source_name                                                               **
**                                                                                             **
**                                                                                             **
**          $dateandtimeandstuffofthings                                                       **
**                                                                                             **
**                                                                                             **
** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

EOF

echo "#include <iostream>" >> $mm
echo "" >> $mm
echo "int       main(void)" >> $mm
echo "{" >> $mm
echo "    return 0;" >> $mm
echo "}" >> $mm