#!/usr/bin/env python
import sys
import datetime


if len(sys.argv) > 1:
	nclass = sys.argv[1]
else:
	nclass = ""

hdr = nclass+".hpp"
src = nclass+".cpp"
tmp_src = src+"                                                      "
comment_source_nam = tmp_src[:20]
dateandtimeandstuffofthing=str(datetime.datetime.now())

header = """\
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * **
**                                                                                             **
**          oliver belanger - obelange                                                         **
**          {000000000000000000}                                                               **
**                                                                                             **
**                                                                                             **
**          {000000000000000000000001}                                                         **
**                                                                                             **
**                                                                                             **
** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

""".format(comment_source_nam, dateandtimeandstuffofthing)

wr = []
wr.append(header)

wr.append("#include <iostream>\n\n")

wr.append("#include \"{0}\"\n".format(hdr))

hpp = open(hdr, "r")

blob = hpp.read()

twisform = {}

# for i, line in enumerate(blob.split('\n')):
# 	if i < 10:
# 		continue
# 	print i, line

# hpp.close()



f = open(src, "w")

for x in wr:
	f.write(x)

f.close()















