#!/usr/bin/env python
import sys
import datetime
import glob
from subprocess import check_output, call


curr_dir = check_output(['pwd'])
profile = check_output(["ls ~/.profile"], shell=True)

f = open(profile[:-1], "r")
path_set = False
for line in f.readlines():
	if "export PATH" in line[:20]:
		if curr_dir in line:
			print "tools are already in your path, adding execution rights"
			path_set = True
f.close()

if path_set == False:
	f = open(profile[:-1], "a")
	f.write("export PATH=$PATH:{0}\n".format(curr_dir))
	f.close()
	print "tools has been put into your path"

call(["chmod 700 g*"], shell=True)
print "all generator files in tools dir have been set to executable"

